### PR TITLE
submit method return function

### PR DESCRIPTION
**Pull request by jakub-gawlas**
`submit` method should return function to invoke by onClick event

### CODE REVIEW

**Comment by stubailo** [comment]
Are you sure? I think it was correct before. The `props` function returns an object with a `submit` function. That function, when called, calls `mutate` with the right variables.

**Comment by jakub-gawlas** [comment]
yes, but `submit` is used like that:
```
<div onClick={this.props.submit('apollostack/apollo-client')}>Click me</div>;
```
so `submit` is immediately invoked, another option is use `submit` like that:
```
<div onClick={() => this.props.submit('apollostack/apollo-client')}>Click me</div>;
```

**Comment by stubailo** [comment]
Yeah, I don't think the first way is how people would usually use a callback. But we should add a code snippet of how `submit` would be called in the component (the second snippet) to the docs!

**Comment by jakub-gawlas** [comment]
👍 changed

**Comment by stubailo** [comment]
Looks great, thanks for catching this inconsistency!

**Pull request merged**
