### PR TITLE
fix error with createNetworkInterface arguments

### PR DESCRIPTION
**Pull request by avalla**
createNetworkInterface throws an error when the first argument is a string

### CODE REVIEW

**Comment by stubailo** [comment]
@avalla looks like you are using a prerelease version of Apollo client?

**Comment by avalla** [comment]
Hello, @stubailo package.json:
```
"version": "0.5.0-0"
```
I installed it some hours ago

**Comment by helfer** [comment]
@avalla I think our prerelease was accidentally tagged as latest. For now, please use 0.4.21, which is the latest recommended version.

**Comment by avalla** [comment]
ok :) thanks and excuse me, I was thinking that the documentation were not updated, I will close the pull request.
Bye

**Pull request closed without merging**
