### PR TITLE
Added a note about how to do multiple mutations on a component.

### PR DESCRIPTION
**Pull request by GreenAsJade**
As requested (note: code fragment not tested, yet)

### CODE REVIEW

**Comment by stubailo** [comment]
Two things:

1. Let's put the code snippet on two lines 
2. I think the default name is "mutate" not mutation

**Comment by tmeasday** [comment]
Can we make the note also link to the part where the documentation for `graphql` is?

**Comment by GreenAsJade** [comment]
@stubailo It's not entirely clear to me where I'd break that line :)

I'll suggest something :)

**Comment by tmeasday** [comment]
Looks great. I'm not sure where is best to break the line either but this works.

**Pull request merged**
